ruleset=🇨🇳 Home,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/home.list

[custom]



;设置规则标志位

;ruleset=🇨🇳 Home,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/home.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/Direct.list
ruleset=💬 Ai,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/AI.list

ruleset=🇺🇲 美国网站,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/US.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/ProxyLite.list
ruleset=🌍 HBO,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/HBO.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

;ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
;ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
;ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

;ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list

ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

;ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list

ruleset=🌍 流媒体,https://raw.githubusercontent.com/hyq58/clash_rules/refs/heads/main/streaming.list
;ruleset=🌍 流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位

custom_proxy_group=🚀 节点选择`select`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]hyq58`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]DIRECT
custom_proxy_group=💬 Ai`select`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇺🇲 美国网站`select`[]🇺🇲 美国节点`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🌍 流媒体`select`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🌍 HBO`select`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]🌐 游戏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT

custom_proxy_group=hyq58`load-balance`(hyq58)`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=🇭🇰 香港节点`load-balance`(?=.*(香港|香港 IEPL))^((?!(游戏|3x|4x|5x|10x|20x|体验|中转|失联|海外用户)).)*$`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=🌐 游戏节点`load-balance`(游戏)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`load-balance`(?=.*(新加坡|新加坡 IEPL))^((?!(游戏|3x|4x|5x|10x|20x|体验|中转|失联|海外用户)).)*$`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=🇨🇳 台湾节点`load-balance`(?=.*(台湾|台湾 IEPL))^((?!(游戏|3x|4x|5x|10x|20x|体验|中转|失联|海外用户)).)*$`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=🇺🇲 美国节点`load-balance`(?=.*(美国|美国 IEPL)^((?!(游戏|4x|5x|10x|20x|体验|中转|失联|海外用户)).)*$`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=🇯🇵 日本节点`load-balance`(?=.*(日本|日本 IEPL))^((?!(游戏|3x|4x|5x|10x|20x|体验|中转|失联|海外用户)).)*$`http://www.gstatic.com/generate_204`600,,80

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true


;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true






